export const GET_CART = 'GET_CART'
export const ADD_CART = 'ADD_CART'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'