// PRODUCTS
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'

// CART
export const ADD_CART = 'ADD_CART'

// ORDERS
export const SET_ORDERS = 'SET_ORDERS'