import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {useState, useEffect} from 'react';
import { signIn, signOut, useSession } from 'next-auth/client';
import QR from '@/components/qr';

export async function getServerSideProps(context) {
  // await dbConnect();
  
  // const products = await Product.find({}).exec();

  return {
    props: {
      // products: jsonify(products),
    }
  }
}

export default function Home({}) {
  // const [asyncUsers, setAsyncUsers] = useState([]);
  // const [loading, setLoading] = useState(true);

  // useEffect(() => {
  //   setTimeout(() => {
  //     fetch('/api/users')
  //     .then(res => res.json())
  //     .then(json => {
  //       setAsyncUsers(json);
  //       setLoading(false);
  //     })
  //   }, 1000);
  // }, [])

  const [ session, loading ] = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex justify-center items-center h-screen'>
        <main className=''>
          <QR />
          {!session && 
            <>
              <button onClick={() => signIn()} className="btn bg-black text-white mx-auto">Iniciar Sesión</button>
            </>
          }
          {session && 
            <>
              Bienvenido {session.user.email} <br/>
              <button onClick={() => signOut()} className="btn bg-black text-white mx-auto">Cerrar Sesión</button>
            </>
          }
          <Link href="/menu">
            <button className="btn bg-black text-white mx-auto" type="button">Menu</button>
          </Link>
        </main>
      </div>
    </>
  )
}