import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import {useState, useEffect} from 'react';
import {dbConnect, jsonify } from '@/util/dbConnect';
// import User from '@/models/user';
// import Product from '@/models/product';
import { signIn, signOut, useSession } from 'next-auth/client';

export async function getServerSideProps(context) {
  await dbConnect();
  
  // const products = await Product.find({}).exec();

  return {
    props: {
      // products: jsonify(products),
    }
  }
}

export default function Home({}) {
  // const [asyncUsers, setAsyncUsers] = useState([]);
  // const [loading, setLoading] = useState(true);

  // useEffect(() => {
  //   setTimeout(() => {
  //     fetch('/api/users')
  //     .then(res => res.json())
  //     .then(json => {
  //       setAsyncUsers(json);
  //       setLoading(false);
  //     })
  //   }, 1000);
  // }, [])

  const [ session, loading ] = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && <>
          Not signed in <br/>
          <button onClick={() => signIn()}>Sign in</button>
        </>}
        {session && <>
          Signed in as {session.user.email} <br/>
          <button onClick={() => signOut()}>Sign out</button>
        </>}        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}